### PR TITLE
Fix crashes from AFL run

### PR DESCRIPTION
**Pull request by kblinova**
We ran American Fuzzy Lop on IMF IAB master file reader and discovered a lot of crashes. These are fixes in the asdcplib code base.

### CODE REVIEW

**Comment by jhursty** [comment]
Thanks! All good but for some style:

1. Please return `RESULT_KLV_CODING(__LINE__, __FILE__)` instead of `RESULT_FAIL` in the three new return statements in `src/MXF.cpp `

2. The two changes to `src/h__02_Reader.cpp` should use `
if ( !m_RIP.PairArray.empty() ) {
  if ( m_RIP.PairArray.front().ByteOffset != 0 ) {`
because the two sides of `&&` are not guaranteed to execute in left-to-right order; `m_RIP.PairArray.front().ByteOffset` could still execute even when the array is empty.

**Comment by jhursty** [comment]
accepted, made changes as indicated

**Comment by kblinova** [comment]
Thanks, John!

**Comment by kblinova** [comment]
We have another fix brewing in a few weeks.

**Pull request merged**
