### PR TITLE
Added the JXS functionality again into the core library.

### PR DESCRIPTION
**Pull request by thorfdbg**
Hi John,

this is the second pull request, this time only the core library functionalities. I did not touch the wrap and unwrap functions.

### CODE REVIEW

**Comment by jhursty** [comment]
src/Metadata.h and src/Metadata.cpp are conflicting, I think they should be removed from the PR

**Comment by thorfdbg** [comment]
Sorry, John. I do not understand. These files contain classes I would need. I neither understand the result of the automated make process. The JPEGXS subdescriptor is defined in line 555, not in line 1337, and the code surely compiles fine here on my side, otherwise I wouldn't have commited. Git neither reported any conflicts - so what is going on here?

**Comment by thorfdbg** [comment]
John, for some reason completely unclear to me, some parts of my code were duplicated into the source. I afraid I do not know how this happened. I just removed the duplications and submitted my original code again. Is metadata.cpp/.h automatically generated from some source? If so, from which?

**Comment by jhursty** [comment]
@thorfdbg The tooling that creates Metadata.h and Metadata.cpp is not part of asdcplib. I updated those files to support JPEGXSPictureSubDescriptor in #88

**Comment by thorfdbg** [comment]
Hi John, here is another pull request. As requested, I separated the JXS specifica in AS_02.h and AD_DCP.h out to two new header files and added a command line switch for autoconf to turn on JXS support.

**Comment by thorfdbg** [comment]
Reverted some minor changes.

**Comment by thorfdbg** [comment]
Hi John,

this is the PR based on the comments made from yesterday. AS_DCP.h is merged from your file, CMakelist.txt has been updated.

**Pull request merged**
