### PR TITLE
Replaced ATMOS with IAB terminology

### LINKED ISSUE #15: Incorrect symbols used for Immersive Audio Data Essence Descriptor and SubDescriptor
The library currently outputs:

```
060e2b34.02530105.0e090603.00000000  len:     120 (PrivateDCDataDescriptor)
             InstanceUID = f6417a2c-80a3-46ad-91a7-e19878fabff9
                Locators:
          SubDescriptors:
  a82aa922-ccf2-4494-8b86-d45a8c6040ba
           LinkedTrackID = 2
              SampleRate = 24/1
       ContainerDuration = 27768
        EssenceContainer = 060e2b34.04010105.0e090605.00000000
       DataEssenceCoding = 060e2b34.04010105.0e090604.00000000

060e2b34.02530105.0e090606.00000000  len:      65 (DolbyAtmosSubDescriptor)
             InstanceUID = a82aa922-ccf2-4494-8b86-d45a8c6040ba
                 AtmosID = 4395698a-3c22-4ab1-b3d4-b6784dba9a65
              FirstFrame = 0
         MaxChannelCount = 10
          MaxObjectCount = 118
            AtmosVersion = 1
```

Instead the symbols defined in the [SMPTE register](https://registry.smpte-ra.org/apps/pages/development/) should be used. For example, `PrivateDCDataDescriptor` should be `IADataEssenceDescriptor` and `DolbyAtmosSubDescriptor` should be `IADataEssenceSubDescriptor`

### PR DESCRIPTION
**Pull request by palemieux**
Closes #15 

*only tested on cmake builds*

### CODE REVIEW

**Comment by jhursty** [comment]
I think the patch goes beyond addressing the labeling issue by also changing the API. These changes will break compilation on all projects that rely on the library for IAB (nee Atmos) file accessors.

Speaking for my own work, this will create an epoch in source control beyond which future work must rely on the new API. sed is my friend though, and the disruption would not be too painful if there is general agreement to make the changes. (@palemieux, do you have a sed script you want to share?)

OTOH, changing just the symbol and label strings will address #15 as well. Issues stemming from the presence of antiquated symbols in the API can be addressed by documentation.

I'd like more input from the community before taking such a big step. I'm going to hold this request for two weeks to allow comment. Comments must be submitted to this thread on or before 25 March 2020.

There are only 17 people receiving alerts from this project, so if you know someone affected by this request who might not be listening please pass this message along.

**Comment by palemieux** [comment]
More background below.

>I think the patch goes beyond addressing the labeling issue by also changing the API. 

I started by only changing the labels mentioned in the issue. It unfortunately felt like the cure was worse than the ill: it led to inconsistencies in naming in the code base and would still require changes in client code.

> Issues stemming from the presence of antiquated symbols in the API can be addressed by documentation.

Within the context of D-Cinema, and given the history there, merely changing the external observables, e.g. replacing Atmos with IAB in command line options and dump output, is probably sufficient -- and might in fact not be needed.

Within the context of IMF, using IAB consistently is critical IMHO since ATMOS was never in scope.

> These changes will break compilation on all projects that rely on the library for IAB (nee Atmos) file accessors.

Yes.

> do you have a sed script you want to share?

I do not have one now, but could work on one. Note that some manual work might nevertheless be needed depending on the coding style/conventions on the client side.

> so if you know someone affected by this request who might not be listening please pass this message along.

Looking forward to feedback/thoughts.

**Comment by jpviollet** [comment]
We can’t break existing API. Adding the new IAB symbols without removing existing ATMOS symbols is ok. The current proposal is too risky. We’d like any proposed alternative change to be posted here for review prior to implementation. Thank you in advance.

**Comment by palemieux** [comment]
> Adding the new IAB symbols without removing existing ATMOS symbols is ok. 

This would require duplicating a large number of function calls and structures, in addition to merely duplicating UL definitions. Is that what you are proposing?

> We can’t break existing API. 

Also, are you concerned with D-Cinema and/or IMF?

**Comment by jpviollet** [comment]
We discussed various options allowing to have information about both symbol families with John per phone prior to posting this comment. I'll let him decide to disclose them here. The concern is for both IMF and D-Cinema. Thank you.

**Comment by palemieux** [comment]
> The concern is for both IMF and D-Cinema. Thank you.

I do not see how IMF is germane here since ASDCPLib does not support IAB (or ATMOS) for IMF.

Can you clarify what your concerns are with IMF?

**Comment by jpviollet** [comment]
My apologizes, it was a misunderstanding on my side. There is indeed no impact on IMF.

**Comment by palemieux** [comment]
> My apologizes, it was a misunderstanding on my side. There is indeed no impact on IMF.

Understood. Thanks.

**Comment by palemieux** [comment]
It looks like support for IAB Track Files can be added without any reference to ATMOS symbols. See:

https://github.com/cinecert/asdcplib/pull/33

**Comment by jhursty** [comment]
superseded by IAB track file #45

**Pull request closed without merging**
